'\" t
.\"     Title: bti-shrink-urls
.\"    Author: [see the "AUTHOR" section]
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: March 2009
.\"    Manual: bti-shrink-urls
.\"    Source: bti-shrink-urls
.\"  Language: English
.\"
.TH "BTI\-SHRINK\-URLS" "1" "March 2009" "bti-shrink-urls" "bti-shrink-urls"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
bti-shrink-urls \- convert URLs to a shorter form using a web service
.SH "SYNOPSIS"
.HP \w'\fBbti\fR\ 'u
\fBbti\fR [\fB\-\-escaped\fR] [\fB\-\-help\fR] [\fBURL\fR]
.SH "DESCRIPTION"
.PP
bti\-shrink\-urls converts URLs to a shorter form using a web service\&.
.PP
Currently http://2tu\&.us/ (default) and http://bit\&.ly / http://j\&.mp are supported\&.
.SH "OPTIONS"
.PP
\fB\-\-escaped\fR
.RS 4
Don\'t escape special characters in the URL any more, they are already percent encoded\&.
.RE
.PP
\fB\-\-help\fR
.RS 4
Print help text\&.
.RE
.PP
\fBURL\fR
.RS 4
Specify the URL to be converted\&. If no URL is given bti\-shrink\-urls waits for input on stdin\&.
.RE
.SH "CONFIGURATION"
.PP
bti\-shrink\-urls is configured by setting some values in ~/\&.bti:
.PP
\fBshrink_host\fR
.RS 4
Possible values: 2tu\&.us (default), bit\&.ly, j\&.mp
.RE
.PP
\fBshrink_bitly_login\fR
.RS 4
API login for bit\&.ly, j\&.mp, required if shrink_host is set to bit\&.ly or j\&.mp\&. See https://code\&.google\&.com/p/bitly\-api/wiki/ApiDocumentation
.RE
.PP
\fBshrink_bitly_key\fR
.RS 4
API key for bit\&.ly, j\&.mp, required if shrink_host is set to bit\&.ly or j\&.mp\&. See https://code\&.google\&.com/p/bitly\-api/wiki/ApiDocumentation
.RE
.SH "AUTHOR"
.PP
Written by Bart Trojanowski
bart@jukie\&.net\&.
.SH "COPYRIGHT AND LICENSE"
.PP
Copyright (C) 2009 Bart Trojanowski
bart@jukie\&.net\&.
.PP
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation version 2 of the License\&.
