.\"     Title: bti
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: May 2008
.\"    Manual: bti
.\"    Source: bti
.\"
.TH "BTI" "1" "May 2008" "bti" "bti"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
bti - send a tweet to twitter.com from stdinput
.SH "SYNOPSIS"
.HP 4
\fBbti\fR [\fB\-\-account\ account\fR] [\fB\-\-password\ password\fR] [\fB\-\-clean\fR] [\fB\-\-debug\fR] [\fB\-\-version\fR] [\fB\-\-help\fR]
.SH "DESCRIPTION"
.PP
bti sends a twitter message to twitter\.com\.
.SH "OPTIONS"
.PP
\fB\-\-account account\fR
.RS 4
Specify the twitter\.com account name\.
.RE
.PP
\fB\-\-password password\fR
.RS 4
Specify the password of your twitter\.com account\.
.RE
.PP
\fB\-\-debug\fR
.RS 4
Print a whole bunch of debugging messages to stdout\.
.RE
.PP
\fB\-\-clean\fR
.RS 4
Don\'t put the working directory and the \'$\' in the twitter message\.
.RE
.PP
\fB\-\-version\fR
.RS 4
Print version number\.
.RE
.PP
\fB\-\-help\fR
.RS 4
Print help text\.
.RE
.SH "AUTHOR"
.PP
Written by Greg Kroah\-Hartman
<greg@kroah\.com>\.
